
interface btVector3 {
  void btVector3();
  void btVector3(float x, float y, float z);
  float x();
  float y();
  float z();
};


interface btVector4 {
  void btVector4();
  void btVector4(float x, float y, float z, float w);
  float w();
};
btVector4 implements btVector3;

interface btQuaternion {
  void btQuaternion(float x, float y, float z, float w);
};
btQuaternion implements btVector4; // this seems wrong? btQuadWord?

interface btTransform {
  void btTransform();
  void btTransform([NonPointer] btQuaternion q, [NonPointer] btVector3 v);

  void setIdentity();
  [NonPointer] btVector3 getOrigin();
  [Copy] btQuaternion getRotation();
};

